name: WaterSatSolver
main: at.jku.complexity.watersatsolver.WaterSatSolverPlugin
version: 0.1
author: JonathanDotExe
load: STARTUP
api-version: 1.21
commands: 
  generatecnf:
    description: Creates a water problem machine for the given cnf
    usage: /generatecnf <cnf>